export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-100">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
        <p className="text-gray-400 text-sm mb-10">Effective date: May 10, 2026</p>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Overview</h2>
          <p className="text-gray-300 leading-relaxed">
            BluTask ("we", "us", or "our") is committed to protecting your privacy. This Privacy
            Policy explains what information we collect, how we use it, and the choices you have.
            By using BluTask you agree to the practices described here.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Information We Collect</h2>
          <p className="text-gray-300 leading-relaxed mb-3">
            We collect only the information needed to provide the BluTask service:
          </p>
          <ul className="list-disc list-inside space-y-2 text-gray-300">
            <li><span className="text-gray-100 font-medium">Account information</span> — your email address and display name, provided when you sign up or sign in with Google or Apple.</li>
            <li><span className="text-gray-100 font-medium">App content</span> — tasks, school assignments, and calendar events you create inside the app.</li>
            <li><span className="text-gray-100 font-medium">Push notification tokens</span> — a device token generated by your operating system if you grant notification permission. Used only to deliver notifications from BluTask to your device.</li>
            <li><span className="text-gray-100 font-medium">Usage and error data</span> — basic diagnostic information to identify and fix crashes. This data does not identify you personally.</li>
          </ul>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">How We Use Your Information</h2>
          <ul className="list-disc list-inside space-y-2 text-gray-300">
            <li>To provide, maintain, and improve the BluTask service.</li>
            <li>To sync your data across your devices.</li>
            <li>To send push notifications you have opted in to receive.</li>
            <li>To respond to support requests you submit.</li>
          </ul>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Data Storage</h2>
          <p className="text-gray-300 leading-relaxed">
            Your data is stored securely using{" "}
            <span className="text-gray-100 font-medium">Supabase</span>, a managed database
            platform hosted on Amazon Web Services (AWS). Data is encrypted in transit using TLS
            and at rest using AES-256. Supabase's infrastructure complies with SOC 2 Type II.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Data Sharing</h2>
          <p className="text-gray-300 leading-relaxed">
            We do not sell, rent, or trade your personal information to third parties. We do not
            share your data with advertisers. We may share data only when required by law or with
            service providers strictly necessary to operate BluTask (such as Supabase for data
            storage), under confidentiality obligations.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Sign In with Google and Apple</h2>
          <p className="text-gray-300 leading-relaxed">
            BluTask supports OAuth sign-in through Google and Apple. When you choose this option,
            the respective provider authenticates you and shares a minimal profile (email and name)
            with us. We do not receive your Google or Apple passwords. Your use of those services
            is also governed by Google's and Apple's own privacy policies.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Push Notifications</h2>
          <p className="text-gray-300 leading-relaxed">
            Push notifications are entirely optional. You can grant or revoke permission at any
            time in your device's Settings app. If you decline permission, no notification token
            is stored and no notifications are sent. Revoking permission disables future
            notifications immediately.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Data Retention and Deletion</h2>
          <p className="text-gray-300 leading-relaxed">
            We retain your data for as long as your account is active. You may delete your account
            and all associated data at any time by contacting us at{" "}
            <a href="mailto:samerbaderwork@gmail.com" className="text-blue-400 hover:text-blue-300 underline">
              samerbaderwork@gmail.com
            </a>
            . Upon confirmed deletion, your data is permanently removed from our systems within 30
            days.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Children's Privacy</h2>
          <p className="text-gray-300 leading-relaxed">
            BluTask is rated 4+ and contains no objectionable content. We do not knowingly collect
            personal information from children under the age of 13. If you believe a child has
            provided us with personal data, please contact us so we can remove it.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Changes to This Policy</h2>
          <p className="text-gray-300 leading-relaxed">
            We may update this Privacy Policy from time to time. When we do, we will revise the
            effective date at the top of this page. Continued use of BluTask after changes are
            posted constitutes your acceptance of the updated policy.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Contact</h2>
          <p className="text-gray-300 leading-relaxed">
            If you have any questions or requests regarding this Privacy Policy, please contact us
            at{" "}
            <a href="mailto:samerbaderwork@gmail.com" className="text-blue-400 hover:text-blue-300 underline">
              samerbaderwork@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  )
}
